RCPS-156 User Management System: Create Documentation for Student Model
RoCS2024/user-management-system pull request #44
Opened 2024-04-08 14:46 UTC by kylmrcdr123

This is the documentation for the student model of user management system

2024-04-09 14:11 UTC, RoCS2024 commented on src/main/java/com/user/management/appl/model/student/Student.java
>       * This is the Student getter and setter.
what is this?

2024-04-09 14:11 UTC, RoCS2024 commented on src/main/java/com/user/management/appl/model/student/Student.java
>      private String studentId;
remove documentation on private properties

2024-04-09 14:11 UTC, RoCS2024 requested changes
see comments

2024-04-09 14:17 UTC, kylmrcdr123 commented on src/main/java/com/user/management/appl/model/student/Student.java
>      private String studentId;
noted po

2024-04-10 12:12 UTC, RoCS2024 commented on src/main/java/com/user/management/appl/model/student/Student.java
>       * This is the Student getter and setter.
still did not remove

2024-04-10 12:12 UTC, RoCS2024 requested changes
see one last comment

2024-04-10 14:23 UTC, RoCS2024 approved these changes
all good

2024-04-10 15:06 UTC, merged