User Management
RoCS2024/user-management-system pull request #8
Opened 2024-03-05 02:10 UTC by katieann7

2024-03-05 09:42 UTC, RoCS2024 requested changes
remove integrated from the project name

2024-03-05 10:51 UTC, katieann7 commented
Done po sir

2024-03-05 11:01 UTC, RoCS2024 commented on user-management-application/build.xml
> +<project name="Ant Test Project" default="build">
project name is Ant Test Project

2024-03-05 11:01 UTC, RoCS2024 commented on user-management-application/ivy.xml
> +    <dependencies>
how about unit test jars?

2024-03-05 11:03 UTC, RoCS2024 commented on user-management-application/src/main/java/com/user/management/data/connection/ConnectionHelper.java
>  package com.user.management.data.connection;
why also delete ConnectionHelper?

2024-03-05 11:03 UTC, RoCS2024 commented on user-management-application/src/main/java/com/user/management/data/user/dao/impl/UserDaoImpl.java
> +public class UserDaoImpl {
where's implements UserDao?

2024-03-05 11:03 UTC, RoCS2024 commented on user-management-application/src/main/java/com/user/management/app/facade/user/impl/UserFacadeImpl.java
> +public class UserFacadeImpl {
where is implements UserFacade?

2024-03-05 11:05 UTC, RoCS2024 requested changes
see comments

2024-03-05 11:05 UTC, JustineDaveMagnaye approved these changes

2024-03-06 03:02 UTC, katieann7 commented
Done na po sir

2024-03-06 05:37 UTC, RoCS2024 approved these changes
all good.

2024-03-06 05:54 UTC, merged